services:
  mongodb:
    image: mongo:7
    container_name: final-project-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  dgraph:
    image: dgraph/standalone:v23.1.1
    container_name: final-project-dgraph
    ports:
      - "8080:8080"
      - "9080:9080"
    volumes:
      - dgraph-data:/dgraph

volumes:
  mongo-data:
  dgraph-data:
